# Generated by Django 5.1.3 on 2024-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0005_alter_meetingtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('08:50 - 09:50', '08:50 - 09:50'), ('09:50 - 10:45', '09:50 - 10:45'), ('11:00 - 11:55', '11:00 - 11:55'), ('11:55 - 12:50', '11:55 - 12:50'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00')], default='11:30 - 12:30', max_length=50),
        ),
    ]
